### PR TITLE
render: egl: Use current display to restore NULL context

### LINKED ISSUE #2327: wlr_egl_restore_context() fails when context->display == NULL
When no context is current `wlr_egl_save_context()` will set `context->display = NULL` and `eglMakeCurrent()` doesn't like that. See https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglMakeCurrent.xhtml:

> As with other commands taking EGLDisplay parameters, if display is not a valid EGLDisplay handle, an EGL_BAD_DISPLAY error is generated. (Some implementations have chosen to allow EGL_NO_DISPLAY as a valid display parameter for eglMakeCurrent. This behavior is not portable to all EGL implementations, and should be considered as an undocumented vendor extension).

This results in an error:
```
[EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
```

### PR DESCRIPTION
**Pull request by any1**
eglGetCurrentDisplay() returns NULL when there is no context current and
eglMakeCurrent() needs a display argument.

Fixes #2327

### CODE REVIEW

**Comment by emersion** [comment]
I think the current usage is okay:

> To release the current context without assigning a new one, set context to EGL_NO_CONTEXT and set draw and read to EGL_NO_SURFACE. […] This is the only case where an uninitialized display may be passed to eglMakeCurrent.

**Comment by emersion** [comment]
Ah, maybe not. "not a valid EGLDisplay handle" is different from "uninitialized".

File: render/egl.c [hunk 1]
```diff
@@ -459,7 +459,9 @@ void wlr_egl_save_context(struct wlr_egl_context *context) {
 }
 
 bool wlr_egl_restore_context(struct wlr_egl_context *context) {
-	return eglMakeCurrent(context->display, context->draw_surface,
+	EGLDisplay display = context->display ?
+		context->display : eglGetCurrentDisplay();
```
Comment (emersion) [inline render/egl.c:463]: `eglGetCurrentDisplay` can return `EGL_NO_DISPLAY` as well

Comment (any1) [reply render/egl.c:463]: Yes, but this is not an actual use case.

Comment (any1) [reply render/egl.c:463]: Actually, perhaps it's safe to say that `context->display == eglGetCurrentDisplay() == EGL_NO_DISPLAY` means that there was and is no context, so no action needs to be taken.

Comment (emersion) [reply render/egl.c:463]: Yeah, LGTM

Comment (any1) [reply render/egl.c:466]: Updated

Comment (any1) [reply render/egl.c:466]: Oh, oops. Need to fix one thing!

Comment (any1) [reply render/egl.c]: Fixed now

File: render/egl.c [hunk 2]
```diff
@@ -459,8 +459,18 @@ void wlr_egl_save_context(struct wlr_egl_context *context) {
...
+	// If the saved context is a null-context, we must use the current
+	// display instead of the saved display because eglMakeCurrent() can't
+	// handle EGL_NO_DISPLAY.
+	EGLDisplay display = context->display == EGL_NO_DISPLAY ?
+		eglGetCurrentDisplay() : context->display;
+
+	// If the current display is also EGL_NO_DISPLAY, we assume that there
+	// is currently no context set and no action needs to be taken to unset
+	// the context.
+	return display == EGL_NO_DISPLAY ? true :
```
Comment (emersion) [inline render/egl.c:471]: Hmm, this is a little bit hard to read. Could we switch to a more common `if`?

Comment (any1) [reply render/egl.c]: Done

File: render/egl.c [hunk 3]
```diff
@@ -459,7 +459,19 @@ void wlr_egl_save_context(struct wlr_egl_context *context) {
...
+	// If the saved context is a null-context, we must use the current
+	// display instead of the saved display because eglMakeCurrent() can't
+	// handle EGL_NO_DISPLAY.
+	EGLDisplay display = context->display == EGL_NO_DISPLAY ?
+		eglGetCurrentDisplay() : context->display;
+
+	// If the current display is also EGL_NO_DISPLAY, we assume that there
+	// is currently no context set and no action needs to be taken to unset
+	// the context.
+	if (display == EGL_NO_DISPLAY)
```
Comment (emersion) [inline render/egl.c:471]: Style: braces are mandatory

Comment (any1) [reply render/egl.c]: oops, done
