### PR TITLE
Fix cursor hotspot update

### LINKED ISSUE #581: Cursor jumps  on decoration border enter in DRM backend
Introduced in #570 with decoration support.

To reproduce:

Enter a decoration border. In the first few pixels of entry, the cursor resize edge xcursor will appear and upon the next move, it will "jump" to (I think) what is the correct position.

Issue is not present on the X11 or Wayland backend.

### PR DESCRIPTION
**Pull request by emersion**
Fixes #581
~~Depends on #710~~

Tried to do not update the output when a new cursor image is set and the cursor isn't visible, but in the end IMHO it's not worth it: it complicates the DRM code and the benefits are too low.

### CODE REVIEW

**Comment by emersion** [comment]
This PR is ready for review.

File: backend/drm/drm.c [hunk 1]
```diff
@@ -602,12 +602,26 @@ static bool wlr_drm_connector_set_cursor(struct wlr_output *output,
...
+			plane->cursor_hotspot_y != hotspot.y) {
+		// Update cursor hotspot
+		conn->cursor_x -= hotspot.x - plane->cursor_hotspot_x;
+		conn->cursor_y -= hotspot.y - plane->cursor_hotspot_y;
+		plane->cursor_hotspot_x = hotspot.x;
+		plane->cursor_hotspot_y = hotspot.y;
+
+		bool ok = drm->iface->crtc_move_cursor(drm, conn->crtc, conn->cursor_x,
+			conn->cursor_y);
+		if (!ok) {
```
Comment (SirCmpwn) [inline backend/drm/drm.c]: I don't think this ok variable needs to exist

Comment (emersion) [reply backend/drm/drm.c]: Fixed
