### PR TITLE
Drop EGL from wlr_renderer_autocreate

### LINKED ISSUE #2563: Drop EGL things from wlr_renderer_autocreate
Currently `wlr_renderer_autocreate` takes parameters tied to EGL:

1. `EGLint *config_attribs, EGLint visual_id`: with https://github.com/swaywm/wlroots/pull/2562, no one uses those anymore.
2. `EGLenum platform, void *remote_display`: almost everyone uses the GBM platform. The only exception is the Wayland backend, which still has no other way to get the DRM FD used by the parent compositor.

The long-term solution for (2) is to get the DRM FD from dmabuf-hints, however the protocol is still pending. A more realistic solution would be to vendor a copy of the `wl_drm` protocol, which Mesa uses exactly for this.

Once that is done, we can think of picking a new signature for `wlr_renderer_autocreate`. The renderer needs to have access to the DRM FD to initialize itself. There may not be a DRM FD, e.g. on GPU-less setups, in which case we should allow `wlr_renderer_autocreate` to create a software renderer.

Possible new signatures:

```c
/**
 * Automatically create a renderer with the provided DRM FD.
 * Maybe this is too DRM-specific?
 */
struct wlr_renderer *wlr_renderer_autocreate(int drm_fd);

/**
 * Automatically create a renderer suitable for the backend.
 * The rendering device will be queried from the backend.
 */
struct wlr_renderer *wlr_renderer_autocreate(struct wlr_backend *backend);
```

### PR DESCRIPTION
**Pull request by bl4ckb0ne**
Fixes #2563, requires https://github.com/swaywm/wlroots/pull/2613

* * *
Breaking change: `wlr_renderer_autocreate` no longer takes the arguments `EGLenum platform, void *remote_display`. Instead it takes a `struct wlr_backend *`.

### CODE REVIEW

File: render/wlr_renderer.c [hunk 1]
```diff
@@ -247,9 +249,10 @@ bool wlr_renderer_init_wl_display(struct wlr_renderer *r,
 	return true;
 }
 
-struct wlr_renderer *wlr_renderer_autocreate(EGLenum platform,
-		void *remote_display) {
-	struct wlr_egl *egl = wlr_egl_create(platform, remote_display, NULL);
+struct wlr_renderer *wlr_renderer_autocreate(struct wlr_backend *backend) {
+	int fd = backend_get_drm_fd(backend);
```
Comment (emersion) [inline render/wlr_renderer.c:253]: We need to fail if `fd < 0`.

File: render/wlr_renderer.c [hunk 2]
```diff
@@ -247,9 +249,10 @@ bool wlr_renderer_init_wl_display(struct wlr_renderer *r,
...
+	struct wlr_egl *egl = wlr_egl_create(EGL_PLATFORM_GBM_KHR,
+			gbm_create_device(fd), NULL);
```
Comment (emersion) [inline render/wlr_renderer.c:255]: We need to handle `gbm_create_device` failures by checking whether it returns NULL here.

Comment (emersion) [inline render/wlr_renderer.c:255]: When the `wlr_egl` is destroyed, we need to destroy the GBM device.

A simple fix would be to add a `struct gbm_device *` field to `wlr_egl`.

**Review by emersion — CHANGES_REQUESTED** [review]
The meat of the patch looks good.

Can you squash the last two commits together? Each commit should compile correctly, otherwise that makes bisecting difficult.

**Comment by emersion** [comment]
Also, I think we can drop the `<wlr/render/egl.h>` include from `include/wlr/render/wlr_renderer.h`.

File: render/wlr_renderer.c (hunk 1 above)
Comment (bl4ckb0ne) [reply render/wlr_renderer.c:253]: Could it be 0 or is it already checked when initializing it in the backends?

Comment (emersion) [reply render/wlr_renderer.c:253]: 0 is a valid FD. For instance, if a compositor closes stdout and then opens a DRM FD, that FD would be assigned the number 0. Yes, it's misleading.

Comment (emersion) [reply render/wlr_renderer.c:253]: The check should be `< 0`, not `== 0`.

File: include/wlr/render/egl.h [hunk 3]
```diff
@@ -24,6 +24,7 @@
 #include <EGL/egl.h>
 #include <EGL/eglext.h>
 #include <pixman.h>
+#include <gbm.h>
```
Comment (emersion) [inline include/wlr/render/egl.h:27]: We don't actually need to include this header, I think. It should work fine without.

File: render/wlr_renderer.c [hunk 4]
```diff
@@ -247,14 +249,29 @@ bool wlr_renderer_init_wl_display(struct wlr_renderer *r,
 	return true;
 }
 
-struct wlr_renderer *wlr_renderer_autocreate(EGLenum platform,
-		void *remote_display) {
-	struct wlr_egl *egl = wlr_egl_create(platform, remote_display, NULL);
+struct wlr_renderer *wlr_renderer_autocreate(struct wlr_backend *backend) {
+	int fd = backend_get_drm_fd(backend);
+	if (fd == 0) {
+		wlr_log(WLR_ERROR, "Invalid DRM fd");
```
Comment (emersion) [inline render/wlr_renderer.c:255]: A better error message might be "Failed to get DRM FD from backend".

File: render/wlr_renderer.c (hunk 1 above)
Comment (bl4ckb0ne) [reply render/wlr_renderer.c:253]: Oh derp

File: include/wlr/render/egl.h (hunk 3 above)
Comment (bl4ckb0ne) [reply include/wlr/render/egl.h]: I moved it to the `egl.c` file where it's needed for the `gbm_destroy_device` call

File: render/wlr_renderer.c (hunk 4 above)
Comment (bl4ckb0ne) [reply render/wlr_renderer.c]: Makes more sense yeah

File: render/wlr_renderer.c (hunk 2 above)
Comment (bl4ckb0ne) [reply render/wlr_renderer.c]: Done

Comment (bl4ckb0ne) [reply render/wlr_renderer.c]: Done

**Comment by bl4ckb0ne** [comment]
I dropped the `egl.h` header from the `wlr_renderer` one, but it's required in the backends when getting the `wlr_egl` from the `wlr_gles_renderer`.

File: include/wlr/render/egl.h (hunk 3 above)
Comment (emersion) [reply include/wlr/render/egl.h]: Cool. It seems this line was still added in this commit (and removed in the next one), fixed it locally.

**Review by emersion — APPROVED** [review]
LGTM, thanks!
