### PR TITLE
Fix popups position for rotated views

### LINKED ISSUE #415: xdg-shell popups don't work anymore on rotated views
1. Open `gnome-calculator`
2. Rotate it
3. Open the combobox
4. It's not at the right position (though, input events work as expected)

This used to work, needs a bisect.

### PR DESCRIPTION
**Pull request by emersion**
Test plan: open `gnome-calculator`, rotate it, click on the combobox. Test with a different screen scale factor too.

Fixes #415

### CODE REVIEW

File: rootston/output.c [hunk 1]
```diff
@@ -17,13 +17,40 @@ static inline int64_t timespec_to_msec(const struct timespec *a) {
...
 }
 
+/**
+ * Computes the surface size homogeneous to the global compositor coordinates.
+ */
+static void get_surface_size(struct wlr_surface *surface, double *width,
+		double *height) {
+	double surface_scale = surface->current->scale;
+	*width = (double)surface->current->buffer_width / surface_scale;
+	*height = (double)surface->current->buffer_height / surface_scale;
```
Comment (acrisci) [inline rootston/output.c]: Isn't this already present in `buffer->current->width|height`?

Comment (emersion) [reply rootston/output.c]: You're right, fixed.

File: rootston/output.c [hunk 2]
```diff
@@ -17,13 +17,30 @@ static inline int64_t timespec_to_msec(const struct timespec *a) {
 	return (int64_t)a->tv_sec * 1000 + a->tv_nsec / 1000000;
 }
 
+/**
+ * Rotate a child's position relative to a parent. The parent size is (pw, ph),
+ * the child position is (*sx, *sy) and its size is (sw, sh).
+ */
+static void rotate_child_position(double *sx, double *sy, double sw, double sh,
+		double pw, double ph, float rotation) {
```
Comment (acrisci) [inline rootston/output.c]: Out args generally go last.

Comment (emersion) [reply rootston/output.c]: So this is in _and_ out. Not sure what to do about it. Maybe make it in-only, and add another pair of out arguments?

File: rootston/output.c [hunk 3]
```diff
@@ -95,36 +103,55 @@ static void render_surface(struct wlr_surface *surface,
...
-			popup_y, rotation);
-		render_xdg_v6_popups(popup, desktop, wlr_output, when, popup_x, popup_y,
-			rotation);
+		double popup_width = popup->surface->current->width;
+		double popup_height = popup->surface->current->height;
+
+		double popup_x = surface->geometry->x + popup->popup_state->geometry.x -
+			popup->geometry->x;
+		double popup_y = surface->geometry->y + popup->popup_state->geometry.y -
+			popup->geometry->y;
```
Comment (acrisci) [inline rootston/output.c]: I think this calculation is complicated enough that it needs to be in the wlr-xdg implementation.

File: rootston/output.c (hunk 2 above)
Comment (SirCmpwn) [reply rootston/output.c]: This is an internal rootston function, I don't care

File: rootston/output.c (hunk 3 above)
Comment (emersion) [reply rootston/output.c]: Yeah, will do.

**Comment by acrisci** [comment]
Tested with xdg-popup and subsurfaces and works ok.

Maybe unrelated, but resizing is especially broken with rotated windows.

Will test wl-shell a little later.

**Comment by acrisci** [comment]
Works with wl-shell. Does not work with xwayland.

**Comment by SirCmpwn** [comment]
Thanks!
