### PR TITLE
Redesign GLES2 renderer

### LINKED ISSUE #55: Use GL_KHR_debug
Currently we use a macro (GL_CALL) to wrap around each of the OpenGL functions to check glError and log if anything went wrong. It works, but it's used inconsistently (e.g. outside of wlr-render) and is ugly, in my opinion.

With [this OpenGL extension](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt), we can set log handlers that the OpenGL implementation will call when something goes wrong and actually get better quality debug messages than what we have currently.

A disadvantage of this is that we will lose the ability to print line numbers of where the error specifically happens. The extension does have some ways to get some arbitrary data into the messages, so we could probably do as good as file + function.

### PR DESCRIPTION
**Pull request by emersion**
This ports the GLES2 `wlr_renderer` part of #319. This PR tries not to touch too much to the texture part, which will be redesigned in another PR.

- [x] Use [GL_KHR_debug](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt)
- [x] Remove global state
- [x] ~~Investigate if it's possible to remove some shaders (is the RGBX shader required at all?)~~
- [x] ~~Save output projection in `wlr_renderer_begin`, remove it from `wlr_render_texture`. Should we apply it automatically when the user provides a matrix?~~
- [x] Remove raw GL calls outside the renderer

Fixes #55
Updates #558

### CODE REVIEW

File: render/wlr_renderer.c [hunk 1]
```diff
@@ -17,8 +17,13 @@ void wlr_renderer_destroy(struct wlr_renderer *r) {
...
 
-void wlr_renderer_begin(struct wlr_renderer *r, struct wlr_output *o) {
-	r->impl->begin(r, o);
+void wlr_renderer_begin_raw(struct wlr_renderer *r, uint32_t width,
+		uint32_t height) {
+	r->impl->begin(r, width, height);
+}
+
+void wlr_renderer_begin(struct wlr_renderer *r, struct wlr_output *output) {
+	wlr_renderer_begin_raw(r, output->width, output->height);
```
Comment (SirCmpwn) [inline render/wlr_renderer.c]: I would sooner just make it take a width/height always instead of an output

**Comment by emersion** [comment]
>I would sooner just make it take a width/height always instead of an output

Right, I've done that.

This PR is now ready for review. Let me know if you think something else needs a redesign in `wlr_renderer`.

File: wlroots.syms [hunk 2]
```diff
@@ -39,6 +39,7 @@ WLROOTS_0_0_0 {
         wlr_libinput_tablet_tool_create;
         wlr_libinput_touch_create;
         wlr_log_stderr;
+        wlr_renderer_begin_raw;
```
Comment (SirCmpwn) [inline wlroots.syms]: remove

File: backend/drm/drm.c [hunk 3]
```diff
@@ -643,14 +643,13 @@ static bool wlr_drm_connector_set_cursor(struct wlr_output *output,
...
+		wlr_renderer_begin(rend, plane->surf.width, plane->surf.height);
+		wlr_renderer_clear(rend, (float[]){ 0.0, 0.0, 0.0, 0.0 });
+		wlr_render_texture(rend, plane->wlr_tex, plane->matrix, 0, 0, 1.0f);
+		wlr_renderer_end(rend);
 
-		wlr_render_texture(plane->surf.renderer->wlr_rend, plane->wlr_tex,
-			plane->matrix, 0, 0, 1.0f);
-
-		glFinish();
+		// TODO: remove these raw GL calls
```
Comment (ascent12) [inline backend/drm/drm.c]: Didn't I originally write a function for this?

Comment (emersion) [reply backend/drm/drm.c]: Yeah, but it's reading pixel lines one by one in a loop. I wonder if I:
* Should use it anyway
* Should add a `bool invert_y` parameter to be able to use only one GL call
* Should keep it as is until there's a better solution

**Comment by emersion** [comment]
>This LGTM, I ran some tests with dmabuf and egl and didn't see any regressions.

Nice, thanks for testing!

File: backend/drm/drm.c (hunk 3 above)
Comment (ascent12) [reply backend/drm/drm.c]: There is a way it can be done in one call (GL_PACK_ROW_LENGTH), but as usual, it requires a version later than GLES2 (and is not available via extensions), so I was stuck doing it the stupid, inefficient way.

Comment (emersion) [reply backend/drm/drm.c]: Yeah. But you would still need to invert the y axis after that right? I didn't find a way to do this with GLES3 (it's possible to do so when rendering, not when reading pixels). Maybe we should make `wlr_renderer_read_pixels` always read pixels with an inverted y axis?

Anyway, I've pushed a commit to use the inefficient way.

**Comment by SirCmpwn** [comment]
Tested, works, please fix conflicts

**Comment by emersion** [comment]
Done!

**Comment by SirCmpwn** [comment]
Thanks!
