### PR TITLE
xwayland/selection: fix self-copy loop 

### LINKED ISSUE #2192: Pasting in Emacs causes wlroots to run out of pipes
* Step to reproduce
1) Open emacs
2) Paste some text from the primary clipboard
4) Emacs and any other GUI application crash
After that I can't open any applications but sway still works.

When I use my usual config the first thing to crash is redshift and after a few seconds every window crash. 

* Sway Version:
sway version 1.4-a8a6ed66 (May 11 2020, branch 'master')

* Debug Log:
https://gist.github.com/mssdvd/d00ef14c7df092dfed9c582abd8aedc0

* Configuration File:
````
bindsym Mod4+c exec clipman pick -t rofi
exec wl-paste -t text --watch clipman store
include /etc/sway/config
include /etc/sway/config.d/*
````
* Stack Trace:
None because Sway didn't crash

### PR DESCRIPTION
**Pull request by Xyene**
See commits for details.

Fixes #2192.

### CODE REVIEW

File: xwayland/selection/outgoing.c [hunk 1]
```diff
@@ -392,6 +392,12 @@ void xwm_handle_selection_request(struct wlr_xwm *xwm,
 		goto fail_notify_requestor;
 	}
 
+	if (req->time <= selection->timestamp) {
+		wlr_log(WLR_DEBUG, "ignoring old request from timestamp %d; expecting > %d",
+				req->time, selection->timestamp);
+		goto fail_notify_requestor;
+	}
+
```
Comment (Xyene) [inline xwayland/selection/outgoing.c:400]: From ICCCM:

> The specified owner and selection will be the values that were specified in the SetSelectionOwner request. The owner should compare the timestamp with the period it has owned the selection and, if the time is outside, refuse the SelectionRequest by sending the requestor window a SelectionNotify event with the property set to None (by means of a SendEvent request with an empty event mask).

File: xwayland/selection/incoming.c [hunk 2]
```diff
@@ -492,8 +492,16 @@ int xwm_handle_xfixes_selection_notify(struct wlr_xwm *xwm,
 		return 0;
 	}
 
+	if (event->timestamp <= selection->timestamp) {
```
Comment (Xyene) [inline xwayland/selection/incoming.c:495]: I'm not sure this block is strictly necessary (never fired in my testing), but I don't think it can hurt.

File: xwayland/selection/outgoing.c (hunk 1 above)
Comment (Xyene) [reply xwayland/selection/outgoing.c:400]: (Note we're not exactly implementing ICCCM's prescribed behavior.)

Comment (Xyene) [reply xwayland/selection/outgoing.c:400]: Prior art: https://invent.kde.org/plasma/kwin/-/blob/master/src/xwl/selection.cpp#L237

Though I think check has to be `<` instead of `<=` for safety, due to limited precision in `xcb_timestamp_t`.

File: xwayland/selection/incoming.c (hunk 2 above)
Comment (Xyene) [reply xwayland/selection/incoming.c:495]: No prior art here; KWin doesn't do this so their selections can go "back in time": https://invent.kde.org/plasma/kwin/-/blob/master/src/xwl/selection.cpp#L106

**Comment by Xyene** [comment]
Oops, this breaks pasting from Firefox into Slack, with:

```
00:18:09.285 [DEBUG] [wlr] [xwayland/selection/outgoing.c:378] XCB_SELECTION_REQUEST (time=0 owner=2097153, requestor=16777225 selection=277, target=404, property=363)
00:18:09.285 [ERROR] [wlr] [xwayland/selection/outgoing.c:397] ignoring old request from timestamp 0; expecting > 1124841
00:18:09.285 [DEBUG] [wlr] [xwayland/selection/outgoing.c:29] SendEvent destination=16777225 SelectionNotify(31) time=0 re
```

I'll have to look for why this works in KWin as it does...

File: xwayland/selection/outgoing.c (hunk 1 above)
Comment (Xyene) [reply xwayland/selection/outgoing.c:400]: KWin doesn't have the `XCB_CURRENT_TIME` check and works because https://invent.kde.org/plasma/kwin/-/blob/master/src/xwl/selection.cpp#L107 moves `m_timestamp` back to 0.

Qt has a similar `XCB_CURRENT_TIME` check to what's introduced in this PR, though: https://github.com/qt/qtbase/blob/658b93386eea34398de3ddacab436601e1ab5bbb/src/plugins/platforms/xcb/qxcbclipboard.cpp#L569-L570

File: xwayland/selection/selection.c [hunk 3]
```diff
@@ -267,12 +267,14 @@ static void xwm_selection_set_owner(struct wlr_xwm_selection *selection,
...
 			selection->atom,
 			XCB_TIME_CURRENT_TIME);
+		xcb_flush(selection->xwm->xcb_conn);
 	} else {
 		if (selection->owner == selection->window) {
 			xcb_set_selection_owner(selection->xwm->xcb_conn,
 				XCB_WINDOW_NONE,
 				selection->atom,
 				selection->timestamp);
+			xcb_flush(selection->xwm->xcb_conn);
```
Comment (Xyene) [inline xwayland/selection/selection.c:277]: Came to this conclusion stepping through the code, but KWin also does this: https://invent.kde.org/plasma/kwin/-/blob/master/src/xwl/selection.cpp#L209

**Review by emersion — APPROVED** [review]
Thanks!
